
import 'package:uuid/uuid.dart';  //? We have to import uuid package to generate unique id
final uuid=Uuid(); //? We have to create object of Uuid class to generate unique id
enum Category {  //? Write enum name in capital letter
  food,
  travel,
  leisure,
  work,
}
class expense {  //? Write class name in small letter
expense({
  required this.title,  
  required this.amount,
  required this.date,
  required this.category}):id=uuid.v4() ; //? We are using initializer list to initialize the id with unique id generated by uuid package


  final String id;
  final String title;
  final double amount ;
  final DateTime date;
  final Category category;
  
}