
import 'package:flutter/material.dart';
import 'package:uuid/uuid.dart';  //? We have to import uuid package to generate unique id
final uuid=Uuid(); //? We have to create object of Uuid class to generate unique id
enum Category {  //? Write enum name in capital letter
  food,
  travel,
  leisure,
  work,
}

const Category_Icons= { //! Make sure to write = after defining Icons Category and write the categories inside {}
  Category.food:Icons.lunch_dining,
  Category.leisure:Icons.movie,
  Category.travel:Icons.flight_takeoff,
  Category.work:Icons.work
};
class Expense { //? Make sure to write class name Expense in capital letter because it'll interfare if you create any list called as expense later in this course inside expense_item.dart
Expense({
  required this.title,  
  required this.amount,
  required this.date,
  required this.category}):id=uuid.v4() ; //? We are using initializer list to initialize the id with unique id generated by uuid package


  final String id;
  final String title;
  final double amount ;
  final DateTime date;
  final Category category;
  
}